### ISSUE TITLE
Monitor connection to VVA

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-monitor#21]
VVA is now a dependency of Caseflow. We should add it as part of the monitoring system.

Steps:
 - [ ] Register a fake VVA service (https://github.com/department-of-veterans-affairs/caseflow-monitor/tree/master/lib/fakes)
 - [ ] Implement real VVA service (https://github.com/department-of-veterans-affairs/caseflow-monitor/tree/master/app/services)
 
Unit test doesn't exist. So either implement one, or ignore it. :)

**Comment by kierachell** [comment]
**PASSED**
![screen shot 2017-07-12 at 7 08 16 am](https://user-images.githubusercontent.com/18075411/28114940-e7a82142-66d0-11e7-99a2-169349008d69.png)
