### ISSUE TITLE
Use more than 1 case number in Monitor query

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-monitor#28]
Connects: https://github.com/department-of-veterans-affairs/appeals-deployment/issues/714

Monitor was not able to capture the VBMS partial outage that we have experienced. It is likely because Monitor is only programmed to use one case number for all of its query. We should consider using a wider range of case numbers to capture the states of external systems.

**Comment by kierachell** [comment]
DONE
