### ISSUE TITLE
Send VACOLS Monitor gauge stats to Datadog

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow-monitor#52]
We poll VACOLS and send gague statistics to prometheus/grafana.  We'd like to send these stats to Datadog as well.  

Bring in the dogstatsd-ruby library and send these stats to datadog. 

Relevant pointers:
https://github.com/department-of-veterans-affairs/caseflow-monitor/blob/master/app/services/vacols_service.rb#L115

https://github.com/DataDog/dogstatsd-ruby

**Comment by emvalenzuela** [comment]
This is now resolved.
