### ISSUE TITLE
VACOLS is shown to be "Down" but VACOLS is functioning as expected

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow-monitor#98]
At https://monitor.cf.ds.va.gov/, the VACOLS box is shown to be "Down" but VACOLS is functioning as expected.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/55255674/86031328-4ee85400-b9fb-11ea-9db2-0b432fa082fc.png">

While this is not blocking any activity, it caused [some alarm with users](https://dsva.slack.com/archives/CHX8FMP28/p1593446399187400).

[Slack convo](https://dsva.slack.com/archives/CAM9FJ85P/p1593445522029800)

## AC
- [ ] VACOLS box shows actual status of VACOLS

**Comment by alisan16** [comment]
This continues to come up for Bat Team, most recently here: https://dsva.slack.com/archives/CHX8FMP28/p1597754868052100

@department-of-veterans-affairs/caseflow-tech-leads do any of your teams have the capacity to take this on in an upcoming sprint?

**Comment by leikkisa** [comment]
@alisan16 Do you have a rough idea of the size of this ticket? I feel like Foxtrot has engineering capacity right now.

**Comment by aroltsch** [comment]
A few places to check:
1. Is the service correctly pinging VACOLS every few minutes? 
2. Does the "ping" return a successful response? 
3. If yes to 1 and 2, then is the UI not being updated correctly?

**Comment by ferristseng** [comment]
Seeing an error in the logs, which seems to correspond with the huge gap in successful queries:

<img width="910" alt="Screen Shot 2020-09-11 at 1 23 32 PM" src="https://user-images.githubusercontent.com/1298274/92956836-8df04800-f435-11ea-8546-5e71efcea487.png">

<img width="1014" alt="Screen Shot 2020-09-11 at 1 26 06 PM" src="https://user-images.githubusercontent.com/1298274/92956949-c09a4080-f435-11ea-80f6-a3dd2ef3ea0a.png">

**Comment by ferristseng** [comment]
I traced the failed query to here:

https://github.com/department-of-veterans-affairs/caseflow-monitor/blob/4b36b6137d01a2e4f06e9229b49117d7f44228bc/app/services/vacols_service.rb#L45-L48

and managed to trigger a `StatementInvalid` error by running in a bunch of times in prod"

VACOLS query failed

```
undefined method `original_exception' for #<ActiveRecord::StatementInvalid:0x0000000003f563f8>
[
"/opt/caseflow-monitor/src/app/services/vacols_service.rb:105:in `rescue in query_service'",
"/opt/caseflow-monitor/src/app/services/vacols_service.rb:44:in `query_service'",
"/opt/caseflow-monitor/src/app/services/monitor_service.rb:81:in `block in query'", "/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'",
"/opt/caseflow-monitor/src/app/services/monitor_service.rb:80:in `query'",
"/opt/caseflow-monitor/src/app/jobs/monitor_job.rb:98:in `block in run_query'"
]
```

**Comment by ferristseng** [comment]
Ok, it looks like `original_exception` was a deprecated function, that's been removed.
I dug in the logs a bit more, and it looks like the `StatementInvalid` exception was wrapping an `OCIError`:

```
W, [2020-09-11T13:53:38.255358 #13265]  WARN -- : OCIException: OCI8 was already closed.:         select user_id from DBA_USERS where username = 'DSUSER'
```

It looks like the code is already designed to recover from an `OCIError`, so I think this is just a matter of using `#cause` instead of `#original_exception`. I am a little bit confused by the distinction of `OCIError` and `OCIException`...so I might need to do a bit of research.

**Comment by nanotone** [comment]
@ferristseng From the docs: https://www.rubydoc.info/github/kubo/ruby-oci8/OCIError

Looks like OCIException is the generic superclass for all exceptions in that library. Whereas OCIError (one such subclass) is like, "something wrong OracleDB-wise" -- it has SQL-related arguments/attributes.

**Comment by ferristseng** [comment]
I actually dug through the source code to make sure the error wasn't a superclass of `OCIException`...it is actually just an `OCIException`:

https://github.com/kubo/ruby-oci8/blob/d03afb257a7a813d56b8b1e12226c22c3e1f15d6/ext/oci8/oci8lib.c#L699-L702
